var podaci = {
  "projekcije": [
    {
      "film": "War Machine",
      "vrijeme": "20:00",
      "sala": "Dvorana 1",
      "trajanje": "110 min",
      "poster": "../slike/war_machine.webp",
      "sjedista": [
        { "red": "A", "broj": 1, "status": "slobodno" }, { "red": "A", "broj": 2, "status": "slobodno" }, { "red": "A", "broj": 3, "status": "zauzeto" }, { "red": "A", "broj": 4, "status": "slobodno" }, { "red": "A", "broj": 5, "status": "zauzeto" }, { "red": "A", "broj": 6, "status": "slobodno" }, { "red": "A", "broj": 7, "status": "slobodno" }, { "red": "A", "broj": 8, "status": "slobodno" }, { "red": "A", "broj": 9, "status": "slobodno" }, { "red": "A", "broj": 10, "status": "slobodno" },
        { "red": "B", "broj": 1, "status": "slobodno" }, { "red": "B", "broj": 2, "status": "zauzeto" }, { "red": "B", "broj": 3, "status": "zauzeto" }, { "red": "B", "broj": 4, "status": "slobodno" }, { "red": "B", "broj": 5, "status": "slobodno" }, { "red": "B", "broj": 6, "status": "slobodno" }, { "red": "B", "broj": 7, "status": "slobodno" }, { "red": "B", "broj": 8, "status": "slobodno" }, { "red": "B", "broj": 9, "status": "slobodno" }, { "red": "B", "broj": 10, "status": "slobodno" },
        { "red": "C", "broj": 1, "status": "slobodno" }, { "red": "C", "broj": 2, "status": "slobodno" }, { "red": "C", "broj": 3, "status": "slobodno" }, { "red": "C", "broj": 4, "status": "slobodno" }, { "red": "C", "broj": 5, "status": "slobodno" }, { "red": "C", "broj": 6, "status": "slobodno" }, { "red": "C", "broj": 7, "status": "slobodno" }, { "red": "C", "broj": 8, "status": "slobodno" }, { "red": "C", "broj": 9, "status": "slobodno" }, { "red": "C", "broj": 10, "status": "slobodno" },
        { "red": "D", "broj": 1, "status": "slobodno" }, { "red": "D", "broj": 2, "status": "slobodno" }, { "red": "D", "broj": 3, "status": "zauzeto" }, { "red": "D", "broj": 4, "status": "slobodno" }, { "red": "D", "broj": 5, "status": "zauzeto" }, { "red": "D", "broj": 6, "status": "zauzeto" }, { "red": "D", "broj": 7, "status": "zauzeto" }, { "red": "D", "broj": 8, "status": "slobodno" }, { "red": "D", "broj": 9, "status": "slobodno" }, { "red": "D", "broj": 10, "status": "slobodno" },
        { "red": "E", "broj": 1, "status": "zauzeto" }, { "red": "E", "broj": 2, "status": "slobodno" }, { "red": "E", "broj": 3, "status": "slobodno" }, { "red": "E", "broj": 4, "status": "slobodno" }, { "red": "E", "broj": 5, "status": "slobodno" }, { "red": "E", "broj": 6, "status": "slobodno" }, { "red": "E", "broj": 7, "status": "slobodno" }, { "red": "E", "broj": 8, "status": "slobodno" }, { "red": "E", "broj": 9, "status": "slobodno" }, { "red": "E", "broj": 10, "status": "slobodno" },
        { "red": "F", "broj": 1, "status": "slobodno" }, { "red": "F", "broj": 2, "status": "slobodno" }, { "red": "F", "broj": 3, "status": "slobodno" }, { "red": "F", "broj": 4, "status": "slobodno" }, { "red": "F", "broj": 5, "status": "slobodno" }, { "red": "F", "broj": 6, "status": "slobodno" }, { "red": "F", "broj": 7, "status": "slobodno" }, { "red": "F", "broj": 8, "status": "slobodno" }, { "red": "F", "broj": 9, "status": "slobodno" }, { "red": "F", "broj": 10, "status": "slobodno" },
        { "red": "G", "broj": 1, "status": "slobodno" }, { "red": "G", "broj": 2, "status": "slobodno" }, { "red": "G", "broj": 3, "status": "slobodno" }, { "red": "G", "broj": 4, "status": "zauzeto" }, { "red": "G", "broj": 5, "status": "slobodno" }, { "red": "G", "broj": 6, "status": "slobodno" }, { "red": "G", "broj": 7, "status": "slobodno" }, { "red": "G", "broj": 8, "status": "slobodno" }, { "red": "G", "broj": 9, "status": "slobodno" }, { "red": "G", "broj": 10, "status": "slobodno" },
        { "red": "H", "broj": 1, "status": "zauzeto" }, { "red": "H", "broj": 2, "status": "slobodno" }, { "red": "H", "broj": 3, "status": "slobodno" }, { "red": "H", "broj": 4, "status": "slobodno" }, { "red": "H", "broj": 5, "status": "slobodno" }, { "red": "H", "broj": 6, "status": "slobodno" }, { "red": "H", "broj": 7, "status": "slobodno" }, { "red": "H", "broj": 8, "status": "slobodno" }, { "red": "H", "broj": 9, "status": "slobodno" }, { "red": "H", "broj": 10, "status": "slobodno" }
      ]
    },
    {
      "film": "Shelter",
      "vrijeme": "21:00",
      "sala": "Dvorana 2",
      "trajanje": "107 min",
      "poster": "../slike/shelter.webp",
      "sjedista": [
        { "red": "A", "broj": 1, "status": "slobodno" }, { "red": "A", "broj": 2, "status": "slobodno" }, { "red": "A", "broj": 3, "status": "slobodno" }, { "red": "A", "broj": 4, "status": "slobodno" }, { "red": "A", "broj": 5, "status": "slobodno" }, { "red": "A", "broj": 6, "status": "slobodno" }, { "red": "A", "broj": 7, "status": "slobodno" }, { "red": "A", "broj": 8, "status": "slobodno" }, { "red": "A", "broj": 9, "status": "slobodno" }, { "red": "A", "broj": 10, "status": "slobodno" },
        { "red": "B", "broj": 1, "status": "slobodno" }, { "red": "B", "broj": 2, "status": "slobodno" }, { "red": "B", "broj": 3, "status": "slobodno" }, { "red": "B", "broj": 4, "status": "slobodno" }, { "red": "B", "broj": 5, "status": "slobodno" }, { "red": "B", "broj": 6, "status": "slobodno" }, { "red": "B", "broj": 7, "status": "slobodno" }, { "red": "B", "broj": 8, "status": "slobodno" }, { "red": "B", "broj": 9, "status": "slobodno" }, { "red": "B", "broj": 10, "status": "slobodno" },
        { "red": "C", "broj": 1, "status": "zauzeto" }, { "red": "C", "broj": 2, "status": "zauzeto" }, { "red": "C", "broj": 3, "status": "slobodno" }, { "red": "C", "broj": 4, "status": "slobodno" }, { "red": "C", "broj": 5, "status": "slobodno" }, { "red": "C", "broj": 6, "status": "slobodno" }, { "red": "C", "broj": 7, "status": "slobodno" }, { "red": "C", "broj": 8, "status": "slobodno" }, { "red": "C", "broj": 9, "status": "slobodno" }, { "red": "C", "broj": 10, "status": "slobodno" },
        { "red": "D", "broj": 1, "status": "slobodno" }, { "red": "D", "broj": 2, "status": "slobodno" }, { "red": "D", "broj": 3, "status": "slobodno" }, { "red": "D", "broj": 4, "status": "slobodno" }, { "red": "D", "broj": 5, "status": "zauzeto" }, { "red": "D", "broj": 6, "status": "zauzeto" }, { "red": "D", "broj": 7, "status": "zauzeto" }, { "red": "D", "broj": 8, "status": "slobodno" }, { "red": "D", "broj": 9, "status": "slobodno" }, { "red": "D", "broj": 10, "status": "slobodno" },
        { "red": "E", "broj": 1, "status": "slobodno" }, { "red": "E", "broj": 2, "status": "slobodno" }, { "red": "E", "broj": 3, "status": "slobodno" }, { "red": "E", "broj": 4, "status": "slobodno" }, { "red": "E", "broj": 5, "status": "zauzeto" }, { "red": "E", "broj": 6, "status": "zauzeto" }, { "red": "E", "broj": 7, "status": "slobodno" }, { "red": "E", "broj": 8, "status": "slobodno" }, { "red": "E", "broj": 9, "status": "slobodno" }, { "red": "E", "broj": 10, "status": "slobodno" },
        { "red": "F", "broj": 1, "status": "zauzeto" }, { "red": "F", "broj": 2, "status": "zauzeto" }, { "red": "F", "broj": 3, "status": "zauzeto" }, { "red": "F", "broj": 4, "status": "slobodno" }, { "red": "F", "broj": 5, "status": "slobodno" }, { "red": "F", "broj": 6, "status": "slobodno" }, { "red": "F", "broj": 7, "status": "slobodno" }, { "red": "F", "broj": 8, "status": "slobodno" }, { "red": "F", "broj": 9, "status": "slobodno" }, { "red": "F", "broj": 10, "status": "slobodno" },
        { "red": "G", "broj": 1, "status": "slobodno" }, { "red": "G", "broj": 2, "status": "slobodno" }, { "red": "G", "broj": 3, "status": "zauzeto" }, { "red": "G", "broj": 4, "status": "zauzeto" }, { "red": "G", "broj": 5, "status": "zauzeto" }, { "red": "G", "broj": 6, "status": "slobodno" }, { "red": "G", "broj": 7, "status": "slobodno" }, { "red": "G", "broj": 8, "status": "slobodno" }, { "red": "G", "broj": 9, "status": "slobodno" }, { "red": "G", "broj": 10, "status": "slobodno" },
        { "red": "H", "broj": 1, "status": "slobodno" }, { "red": "H", "broj": 2, "status": "slobodno" }, { "red": "H", "broj": 3, "status": "slobodno" }, { "red": "H", "broj": 4, "status": "slobodno" }, { "red": "H", "broj": 5, "status": "slobodno" }, { "red": "H", "broj": 6, "status": "slobodno" }, { "red": "H", "broj": 7, "status": "slobodno" }, { "red": "H", "broj": 8, "status": "slobodno" }, { "red": "H", "broj": 9, "status": "slobodno" }, { "red": "H", "broj": 10, "status": "slobodno" }
      ]
    },
    {
      "film": "The Bluff",
      "vrijeme": "22:00",
      "sala": "Dvorana 3",
      "trajanje": "102 min",
      "poster": "../slike/the_bluff.webp",
      "sjedista": [
        { "red": "A", "broj": 1, "status": "slobodno" }, { "red": "A", "broj": 2, "status": "slobodno" }, { "red": "A", "broj": 3, "status": "slobodno" }, { "red": "A", "broj": 4, "status": "slobodno" }, { "red": "A", "broj": 5, "status": "slobodno" }, { "red": "A", "broj": 6, "status": "slobodno" }, { "red": "A", "broj": 7, "status": "slobodno" }, { "red": "A", "broj": 8, "status": "slobodno" }, { "red": "A", "broj": 9, "status": "slobodno" }, { "red": "A", "broj": 10, "status": "slobodno" },
        { "red": "B", "broj": 1, "status": "slobodno" }, { "red": "B", "broj": 2, "status": "slobodno" }, { "red": "B", "broj": 3, "status": "slobodno" }, { "red": "B", "broj": 4, "status": "slobodno" }, { "red": "B", "broj": 5, "status": "slobodno" }, { "red": "B", "broj": 6, "status": "slobodno" }, { "red": "B", "broj": 7, "status": "slobodno" }, { "red": "B", "broj": 8, "status": "slobodno" }, { "red": "B", "broj": 9, "status": "slobodno" }, { "red": "B", "broj": 10, "status": "slobodno" },
        { "red": "C", "broj": 1, "status": "slobodno" }, { "red": "C", "broj": 2, "status": "slobodno" }, { "red": "C", "broj": 3, "status": "slobodno" }, { "red": "C", "broj": 4, "status": "slobodno" }, { "red": "C", "broj": 5, "status": "slobodno" }, { "red": "C", "broj": 6, "status": "slobodno" }, { "red": "C", "broj": 7, "status": "slobodno" }, { "red": "C", "broj": 8, "status": "slobodno" }, { "red": "C", "broj": 9, "status": "slobodno" }, { "red": "C", "broj": 10, "status": "slobodno" },
        { "red": "D", "broj": 1, "status": "slobodno" }, { "red": "D", "broj": 2, "status": "slobodno" }, { "red": "D", "broj": 3, "status": "slobodno" }, { "red": "D", "broj": 4, "status": "slobodno" }, { "red": "D", "broj": 5, "status": "slobodno" }, { "red": "D", "broj": 6, "status": "slobodno" }, { "red": "D", "broj": 7, "status": "slobodno" }, { "red": "D", "broj": 8, "status": "slobodno" }, { "red": "D", "broj": 9, "status": "slobodno" }, { "red": "D", "broj": 10, "status": "slobodno" },
        { "red": "E", "broj": 1, "status": "slobodno" }, { "red": "E", "broj": 2, "status": "slobodno" }, { "red": "E", "broj": 3, "status": "slobodno" }, { "red": "E", "broj": 4, "status": "slobodno" }, { "red": "E", "broj": 5, "status": "slobodno" }, { "red": "E", "broj": 6, "status": "slobodno" }, { "red": "E", "broj": 7, "status": "slobodno" }, { "red": "E", "broj": 8, "status": "slobodno" }, { "red": "E", "broj": 9, "status": "slobodno" }, { "red": "E", "broj": 10, "status": "slobodno" },
        { "red": "F", "broj": 1, "status": "slobodno" }, { "red": "F", "broj": 2, "status": "slobodno" }, { "red": "F", "broj": 3, "status": "slobodno" }, { "red": "F", "broj": 4, "status": "slobodno" }, { "red": "F", "broj": 5, "status": "slobodno" }, { "red": "F", "broj": 6, "status": "slobodno" }, { "red": "F", "broj": 7, "status": "slobodno" }, { "red": "F", "broj": 8, "status": "slobodno" }, { "red": "F", "broj": 9, "status": "slobodno" }, { "red": "F", "broj": 10, "status": "slobodno" },
        { "red": "G", "broj": 1, "status": "slobodno" }, { "red": "G", "broj": 2, "status": "slobodno" }, { "red": "G", "broj": 3, "status": "slobodno" }, { "red": "G", "broj": 4, "status": "slobodno" }, { "red": "G", "broj": 5, "status": "slobodno" }, { "red": "G", "broj": 6, "status": "slobodno" }, { "red": "G", "broj": 7, "status": "slobodno" }, { "red": "G", "broj": 8, "status": "slobodno" }, { "red": "G", "broj": 9, "status": "slobodno" }, { "red": "G", "broj": 10, "status": "slobodno" },
        { "red": "H", "broj": 1, "status": "slobodno" }, { "red": "H", "broj": 2, "status": "slobodno" }, { "red": "H", "broj": 3, "status": "slobodno" }, { "red": "H", "broj": 4, "status": "slobodno" }, { "red": "H", "broj": 5, "status": "slobodno" }, { "red": "H", "broj": 6, "status": "slobodno" }, { "red": "H", "broj": 7, "status": "slobodno" }, { "red": "H", "broj": 8, "status": "slobodno" }, { "red": "H", "broj": 9, "status": "slobodno" }, { "red": "H", "broj": 10, "status": "slobodno" }
      ]
    },
    {
      "film": "Interstellar",
      "vrijeme": "19:00",
      "sala": "Dvorana 1",
      "trajanje": "169 min",
      "poster": "../slike/interstellar.webp",
      "sjedista": [
        { "red": "A", "broj": 1, "status": "zauzeto" }, { "red": "A", "broj": 2, "status": "zauzeto" }, { "red": "A", "broj": 3, "status": "zauzeto" }, { "red": "A", "broj": 4, "status": "slobodno" }, { "red": "A", "broj": 5, "status": "zauzeto" }, { "red": "A", "broj": 6, "status": "zauzeto" }, { "red": "A", "broj": 7, "status": "slobodno" }, { "red": "A", "broj": 8, "status": "slobodno" }, { "red": "A", "broj": 9, "status": "slobodno" }, { "red": "A", "broj": 10, "status": "slobodno" },
        { "red": "B", "broj": 1, "status": "slobodno" }, { "red": "B", "broj": 2, "status": "zauzeto" }, { "red": "B", "broj": 3, "status": "zauzeto" }, { "red": "B", "broj": 4, "status": "zauzeto" }, { "red": "B", "broj": 5, "status": "slobodno" }, { "red": "B", "broj": 6, "status": "slobodno" }, { "red": "B", "broj": 7, "status": "zauzeto" }, { "red": "B", "broj": 8, "status": "zauzeto" }, { "red": "B", "broj": 9, "status": "zauzeto" }, { "red": "B", "broj": 10, "status": "slobodno" },
        { "red": "C", "broj": 1, "status": "slobodno" }, { "red": "C", "broj": 2, "status": "slobodno" }, { "red": "C", "broj": 3, "status": "slobodno" }, { "red": "C", "broj": 4, "status": "zauzeto" }, { "red": "C", "broj": 5, "status": "zauzeto" }, { "red": "C", "broj": 6, "status": "slobodno" }, { "red": "C", "broj": 7, "status": "slobodno" }, { "red": "C", "broj": 8, "status": "slobodno" }, { "red": "C", "broj": 9, "status": "slobodno" }, { "red": "C", "broj": 10, "status": "slobodno" },
        { "red": "D", "broj": 1, "status": "slobodno" }, { "red": "D", "broj": 2, "status": "slobodno" }, { "red": "D", "broj": 3, "status": "slobodno" }, { "red": "D", "broj": 4, "status": "slobodno" }, { "red": "D", "broj": 5, "status": "slobodno" }, { "red": "D", "broj": 6, "status": "slobodno" }, { "red": "D", "broj": 7, "status": "zauzeto" }, { "red": "D", "broj": 8, "status": "zauzeto" }, { "red": "D", "broj": 9, "status": "slobodno" }, { "red": "D", "broj": 10, "status": "slobodno" },
        { "red": "E", "broj": 1, "status": "slobodno" }, { "red": "E", "broj": 2, "status": "slobodno" }, { "red": "E", "broj": 3, "status": "zauzeto" }, { "red": "E", "broj": 4, "status": "zauzeto" }, { "red": "E", "broj": 5, "status": "zauzeto" }, { "red": "E", "broj": 6, "status": "slobodno" }, { "red": "E", "broj": 7, "status": "slobodno" }, { "red": "E", "broj": 8, "status": "slobodno" }, { "red": "E", "broj": 9, "status": "slobodno" }, { "red": "E", "broj": 10, "status": "slobodno" },
        { "red": "F", "broj": 1, "status": "slobodno" }, { "red": "F", "broj": 2, "status": "zauzeto" }, { "red": "F", "broj": 3, "status": "slobodno" }, { "red": "F", "broj": 4, "status": "slobodno" }, { "red": "F", "broj": 5, "status": "slobodno" }, { "red": "F", "broj": 6, "status": "slobodno" }, { "red": "F", "broj": 7, "status": "slobodno" }, { "red": "F", "broj": 8, "status": "slobodno" }, { "red": "F", "broj": 9, "status": "slobodno" }, { "red": "F", "broj": 10, "status": "slobodno" },
        { "red": "G", "broj": 1, "status": "slobodno" }, { "red": "G", "broj": 2, "status": "zauzeto" }, { "red": "G", "broj": 3, "status": "zauzeto" }, { "red": "G", "broj": 4, "status": "slobodno" }, { "red": "G", "broj": 5, "status": "zauzeto" }, { "red": "G", "broj": 6, "status": "zauzeto" }, { "red": "G", "broj": 7, "status": "zauzeto" }, { "red": "G", "broj": 8, "status": "zauzeto" }, { "red": "G", "broj": 9, "status": "slobodno" }, { "red": "G", "broj": 10, "status": "slobodno" },
        { "red": "H", "broj": 1, "status": "slobodno" }, { "red": "H", "broj": 2, "status": "slobodno" }, { "red": "H", "broj": 3, "status": "zauzeto" }, { "red": "H", "broj": 4, "status": "zauzeto" }, { "red": "H", "broj": 5, "status": "slobodno" }, { "red": "H", "broj": 6, "status": "slobodno" }, { "red": "H", "broj": 7, "status": "slobodno" }, { "red": "H", "broj": 8, "status": "slobodno" }, { "red": "H", "broj": 9, "status": "slobodno" }, { "red": "H", "broj": 10, "status": "slobodno" }
      ]
    },
    {
      "film": "The Shawshank Redemption",
      "vrijeme": "20:00",
      "sala": "Dvorana 2",
      "trajanje": "142 min",
      "poster": "../slike/the_shawshank_redemtion.webp",
      "sjedista": [
        { "red": "A", "broj": 1, "status": "slobodno" }, { "red": "A", "broj": 2, "status": "slobodno" }, { "red": "A", "broj": 3, "status": "slobodno" }, { "red": "A", "broj": 4, "status": "slobodno" }, { "red": "A", "broj": 5, "status": "slobodno" }, { "red": "A", "broj": 6, "status": "slobodno" }, { "red": "A", "broj": 7, "status": "slobodno" }, { "red": "A", "broj": 8, "status": "slobodno" }, { "red": "A", "broj": 9, "status": "slobodno" }, { "red": "A", "broj": 10, "status": "slobodno" },
        { "red": "B", "broj": 1, "status": "zauzeto" }, { "red": "B", "broj": 2, "status": "zauzeto" }, { "red": "B", "broj": 3, "status": "zauzeto" }, { "red": "B", "broj": 4, "status": "zauzeto" }, { "red": "B", "broj": 5, "status": "slobodno" }, { "red": "B", "broj": 6, "status": "slobodno" }, { "red": "B", "broj": 7, "status": "slobodno" }, { "red": "B", "broj": 8, "status": "slobodno" }, { "red": "B", "broj": 9, "status": "slobodno" }, { "red": "B", "broj": 10, "status": "slobodno" },
        { "red": "C", "broj": 1, "status": "slobodno" }, { "red": "C", "broj": 2, "status": "slobodno" }, { "red": "C", "broj": 3, "status": "slobodno" }, { "red": "C", "broj": 4, "status": "slobodno" }, { "red": "C", "broj": 5, "status": "slobodno" }, { "red": "C", "broj": 6, "status": "slobodno" }, { "red": "C", "broj": 7, "status": "slobodno" }, { "red": "C", "broj": 8, "status": "slobodno" }, { "red": "C", "broj": 9, "status": "slobodno" }, { "red": "C", "broj": 10, "status": "slobodno" },
        { "red": "D", "broj": 1, "status": "slobodno" }, { "red": "D", "broj": 2, "status": "slobodno" }, { "red": "D", "broj": 3, "status": "slobodno" }, { "red": "D", "broj": 4, "status": "slobodno" }, { "red": "D", "broj": 5, "status": "slobodno" }, { "red": "D", "broj": 6, "status": "slobodno" }, { "red": "D", "broj": 7, "status": "slobodno" }, { "red": "D", "broj": 8, "status": "slobodno" }, { "red": "D", "broj": 9, "status": "slobodno" }, { "red": "D", "broj": 10, "status": "slobodno" },
        { "red": "E", "broj": 1, "status": "slobodno" }, { "red": "E", "broj": 2, "status": "slobodno" }, { "red": "E", "broj": 3, "status": "slobodno" }, { "red": "E", "broj": 4, "status": "zauzeto" }, { "red": "E", "broj": 5, "status": "zauzeto" }, { "red": "E", "broj": 6, "status": "zauzeto" }, { "red": "E", "broj": 7, "status": "zauzeto" }, { "red": "E", "broj": 8, "status": "slobodno" }, { "red": "E", "broj": 9, "status": "slobodno" }, { "red": "E", "broj": 10, "status": "slobodno" },
        { "red": "F", "broj": 1, "status": "slobodno" }, { "red": "F", "broj": 2, "status": "slobodno" }, { "red": "F", "broj": 3, "status": "slobodno" }, { "red": "F", "broj": 4, "status": "slobodno" }, { "red": "F", "broj": 5, "status": "slobodno" }, { "red": "F", "broj": 6, "status": "slobodno" }, { "red": "F", "broj": 7, "status": "slobodno" }, { "red": "F", "broj": 8, "status": "slobodno" }, { "red": "F", "broj": 9, "status": "slobodno" }, { "red": "F", "broj": 10, "status": "slobodno" },
        { "red": "G", "broj": 1, "status": "slobodno" }, { "red": "G", "broj": 2, "status": "slobodno" }, { "red": "G", "broj": 3, "status": "slobodno" }, { "red": "G", "broj": 4, "status": "zauzeto" }, { "red": "G", "broj": 5, "status": "zauzeto" }, { "red": "G", "broj": 6, "status": "zauzeto" }, { "red": "G", "broj": 7, "status": "zauzeto" }, { "red": "G", "broj": 8, "status": "slobodno" }, { "red": "G", "broj": 9, "status": "slobodno" }, { "red": "G", "broj": 10, "status": "slobodno" },
        { "red": "H", "broj": 1, "status": "slobodno" }, { "red": "H", "broj": 2, "status": "slobodno" }, { "red": "H", "broj": 3, "status": "slobodno" }, { "red": "H", "broj": 4, "status": "slobodno" }, { "red": "H", "broj": 5, "status": "slobodno" }, { "red": "H", "broj": 6, "status": "slobodno" }, { "red": "H", "broj": 7, "status": "slobodno" }, { "red": "H", "broj": 8, "status": "slobodno" }, { "red": "H", "broj": 9, "status": "slobodno" }, { "red": "H", "broj": 10, "status": "slobodno" }
      ]
    },
    {
      "film": "The Dark Knight",
      "vrijeme": "20:00",
      "sala": "Dvorana 2",
      "trajanje": "152 min",
      "poster": "../slike/the_dark_knight.webp",
      "sjedista": [
        { "red": "A", "broj": 1, "status": "slobodno" }, { "red": "A", "broj": 2, "status": "zauzeto" }, { "red": "A", "broj": 3, "status": "slobodno" }, { "red": "A", "broj": 4, "status": "slobodno" }, { "red": "A", "broj": 5, "status": "slobodno" }, { "red": "A", "broj": 6, "status": "slobodno" }, { "red": "A", "broj": 7, "status": "slobodno" }, { "red": "A", "broj": 8, "status": "slobodno" }, { "red": "A", "broj": 9, "status": "slobodno" }, { "red": "A", "broj": 10, "status": "slobodno" },
        { "red": "B", "broj": 1, "status": "slobodno" }, { "red": "B", "broj": 2, "status": "slobodno" }, { "red": "B", "broj": 3, "status": "zauzeto" }, { "red": "B", "broj": 4, "status": "slobodno" }, { "red": "B", "broj": 5, "status": "slobodno" }, { "red": "B", "broj": 6, "status": "slobodno" }, { "red": "B", "broj": 7, "status": "slobodno" }, { "red": "B", "broj": 8, "status": "slobodno" }, { "red": "B", "broj": 9, "status": "slobodno" }, { "red": "B", "broj": 10, "status": "slobodno" },
        { "red": "C", "broj": 1, "status": "slobodno" }, { "red": "C", "broj": 2, "status": "zauzeto" }, { "red": "C", "broj": 3, "status": "zauzeto" }, { "red": "C", "broj": 4, "status": "slobodno" }, { "red": "C", "broj": 5, "status": "zauzeto" }, { "red": "C", "broj": 6, "status": "zauzeto" }, { "red": "C", "broj": 7, "status": "zauzeto" }, { "red": "C", "broj": 8, "status": "slobodno" }, { "red": "C", "broj": 9, "status": "slobodno" }, { "red": "C", "broj": 10, "status": "slobodno" },
        { "red": "D", "broj": 1, "status": "slobodno" }, { "red": "D", "broj": 2, "status": "slobodno" }, { "red": "D", "broj": 3, "status": "slobodno" }, { "red": "D", "broj": 4, "status": "slobodno" }, { "red": "D", "broj": 5, "status": "zauzeto" }, { "red": "D", "broj": 6, "status": "zauzeto" }, { "red": "D", "broj": 7, "status": "slobodno" }, { "red": "D", "broj": 8, "status": "zauzeto" }, { "red": "D", "broj": 9, "status": "slobodno" }, { "red": "D", "broj": 10, "status": "slobodno" },
        { "red": "E", "broj": 1, "status": "slobodno" }, { "red": "E", "broj": 2, "status": "slobodno" }, { "red": "E", "broj": 3, "status": "slobodno" }, { "red": "E", "broj": 4, "status": "slobodno" }, { "red": "E", "broj": 5, "status": "slobodno" }, { "red": "E", "broj": 6, "status": "slobodno" }, { "red": "E", "broj": 7, "status": "slobodno" }, { "red": "E", "broj": 8, "status": "slobodno" }, { "red": "E", "broj": 9, "status": "slobodno" }, { "red": "E", "broj": 10, "status": "slobodno" },
        { "red": "F", "broj": 1, "status": "slobodno" }, { "red": "F", "broj": 2, "status": "slobodno" }, { "red": "F", "broj": 3, "status": "slobodno" }, { "red": "F", "broj": 4, "status": "slobodno" }, { "red": "F", "broj": 5, "status": "slobodno" }, { "red": "F", "broj": 6, "status": "slobodno" }, { "red": "F", "broj": 7, "status": "zauzeto" }, { "red": "F", "broj": 8, "status": "slobodno" }, { "red": "F", "broj": 9, "status": "slobodno" }, { "red": "F", "broj": 10, "status": "slobodno" },
        { "red": "G", "broj": 1, "status": "slobodno" }, { "red": "G", "broj": 2, "status": "slobodno" }, { "red": "G", "broj": 3, "status": "zauzeto" }, { "red": "G", "broj": 4, "status": "zauzeto" }, { "red": "G", "broj": 5, "status": "slobodno" }, { "red": "G", "broj": 6, "status": "slobodno" }, { "red": "G", "broj": 7, "status": "slobodno" }, { "red": "G", "broj": 8, "status": "slobodno" }, { "red": "G", "broj": 9, "status": "slobodno" }, { "red": "G", "broj": 10, "status": "slobodno" },
        { "red": "H", "broj": 1, "status": "slobodno" }, { "red": "H", "broj": 2, "status": "slobodno" }, { "red": "H", "broj": 3, "status": "zauzeto" }, { "red": "H", "broj": 4, "status": "slobodno" }, { "red": "H", "broj": 5, "status": "slobodno" }, { "red": "H", "broj": 6, "status": "slobodno" }, { "red": "H", "broj": 7, "status": "slobodno" }, { "red": "H", "broj": 8, "status": "slobodno" }, { "red": "H", "broj": 9, "status": "slobodno" }, { "red": "H", "broj": 10, "status": "slobodno" }
      ]
    },
    {
      "film": "Fight Club",
      "vrijeme": "22:00",
      "sala": "Dvorana 3",
      "trajanje": "139 min",
      "poster": "../slike/fight_club.webp",
      "sjedista": [
        { "red": "A", "broj": 1, "status": "slobodno" }, { "red": "A", "broj": 2, "status": "slobodno" }, { "red": "A", "broj": 3, "status": "slobodno" }, { "red": "A", "broj": 4, "status": "slobodno" }, { "red": "A", "broj": 5, "status": "slobodno" }, { "red": "A", "broj": 6, "status": "slobodno" }, { "red": "A", "broj": 7, "status": "slobodno" }, { "red": "A", "broj": 8, "status": "slobodno" }, { "red": "A", "broj": 9, "status": "slobodno" }, { "red": "A", "broj": 10, "status": "slobodno" },
        { "red": "B", "broj": 1, "status": "slobodno" }, { "red": "B", "broj": 2, "status": "slobodno" }, { "red": "B", "broj": 3, "status": "slobodno" }, { "red": "B", "broj": 4, "status": "slobodno" }, { "red": "B", "broj": 5, "status": "slobodno" }, { "red": "B", "broj": 6, "status": "slobodno" }, { "red": "B", "broj": 7, "status": "slobodno" }, { "red": "B", "broj": 8, "status": "slobodno" }, { "red": "B", "broj": 9, "status": "slobodno" }, { "red": "B", "broj": 10, "status": "slobodno" },
        { "red": "C", "broj": 1, "status": "slobodno" }, { "red": "C", "broj": 2, "status": "zauzeto" }, { "red": "C", "broj": 3, "status": "slobodno" }, { "red": "C", "broj": 4, "status": "slobodno" }, { "red": "C", "broj": 5, "status": "slobodno" }, { "red": "C", "broj": 6, "status": "zauzeto" }, { "red": "C", "broj": 7, "status": "zauzeto" }, { "red": "C", "broj": 8, "status": "zauzeto" }, { "red": "C", "broj": 9, "status": "slobodno" }, { "red": "C", "broj": 10, "status": "slobodno" },
        { "red": "D", "broj": 1, "status": "zauzeto" }, { "red": "D", "broj": 2, "status": "zauzeto" }, { "red": "D", "broj": 3, "status": "slobodno" }, { "red": "D", "broj": 4, "status": "zauzeto" }, { "red": "D", "broj": 5, "status": "zauzeto" }, { "red": "D", "broj": 6, "status": "zauzeto" }, { "red": "D", "broj": 7, "status": "slobodno" }, { "red": "D", "broj": 8, "status": "slobodno" }, { "red": "D", "broj": 9, "status": "slobodno" }, { "red": "D", "broj": 10, "status": "slobodno" },
        { "red": "E", "broj": 1, "status": "slobodno" }, { "red": "E", "broj": 2, "status": "slobodno" }, { "red": "E", "broj": 3, "status": "slobodno" }, { "red": "E", "broj": 4, "status": "slobodno" }, { "red": "E", "broj": 5, "status": "slobodno" }, { "red": "E", "broj": 6, "status": "slobodno" }, { "red": "E", "broj": 7, "status": "slobodno" }, { "red": "E", "broj": 8, "status": "slobodno" }, { "red": "E", "broj": 9, "status": "slobodno" }, { "red": "E", "broj": 10, "status": "slobodno" },
        { "red": "F", "broj": 1, "status": "slobodno" }, { "red": "F", "broj": 2, "status": "slobodno" }, { "red": "F", "broj": 3, "status": "slobodno" }, { "red": "F", "broj": 4, "status": "slobodno" }, { "red": "F", "broj": 5, "status": "slobodno" }, { "red": "F", "broj": 6, "status": "slobodno" }, { "red": "F", "broj": 7, "status": "slobodno" }, { "red": "F", "broj": 8, "status": "zauzeto" }, { "red": "F", "broj": 9, "status": "zauzeto" }, { "red": "F", "broj": 10, "status": "slobodno" },
        { "red": "G", "broj": 1, "status": "zauzeto" }, { "red": "G", "broj": 2, "status": "slobodno" }, { "red": "G", "broj": 3, "status": "zauzeto" }, { "red": "G", "broj": 4, "status": "slobodno" }, { "red": "G", "broj": 5, "status": "slobodno" }, { "red": "G", "broj": 6, "status": "slobodno" }, { "red": "G", "broj": 7, "status": "slobodno" }, { "red": "G", "broj": 8, "status": "slobodno" }, { "red": "G", "broj": 9, "status": "slobodno" }, { "red": "G", "broj": 10, "status": "slobodno" },
        { "red": "H", "broj": 1, "status": "slobodno" }, { "red": "H", "broj": 2, "status": "slobodno" }, { "red": "H", "broj": 3, "status": "zauzeto" }, { "red": "H", "broj": 4, "status": "zauzeto" }, { "red": "H", "broj": 5, "status": "slobodno" }, { "red": "H", "broj": 6, "status": "slobodno" }, { "red": "H", "broj": 7, "status": "slobodno" }, { "red": "H", "broj": 8, "status": "zauzeto" }, { "red": "H", "broj": 9, "status": "zauzeto" }, { "red": "H", "broj": 10, "status": "slobodno" }
      ]
    },
    {
      "film": "Anaconda",
      "vrijeme": "20:00",
      "sala": "Dvorana 1",
      "trajanje": "100 min",
      "poster": "../slike/anaconda.jpg",
      "sjedista": [
        { "red": "A", "broj": 1, "status": "slobodno" }, { "red": "A", "broj": 2, "status": "slobodno" }, { "red": "A", "broj": 3, "status": "slobodno" }, { "red": "A", "broj": 4, "status": "slobodno" }, { "red": "A", "broj": 5, "status": "slobodno" }, { "red": "A", "broj": 6, "status": "slobodno" }, { "red": "A", "broj": 7, "status": "slobodno" }, { "red": "A", "broj": 8, "status": "slobodno" }, { "red": "A", "broj": 9, "status": "slobodno" }, { "red": "A", "broj": 10, "status": "slobodno" },
        { "red": "B", "broj": 1, "status": "slobodno" }, { "red": "B", "broj": 2, "status": "slobodno" }, { "red": "B", "broj": 3, "status": "slobodno" }, { "red": "B", "broj": 4, "status": "slobodno" }, { "red": "B", "broj": 5, "status": "slobodno" }, { "red": "B", "broj": 6, "status": "slobodno" }, { "red": "B", "broj": 7, "status": "slobodno" }, { "red": "B", "broj": 8, "status": "slobodno" }, { "red": "B", "broj": 9, "status": "slobodno" }, { "red": "B", "broj": 10, "status": "slobodno" },
        { "red": "C", "broj": 1, "status": "slobodno" }, { "red": "C", "broj": 2, "status": "slobodno" }, { "red": "C", "broj": 3, "status": "slobodno" }, { "red": "C", "broj": 4, "status": "slobodno" }, { "red": "C", "broj": 5, "status": "slobodno" }, { "red": "C", "broj": 6, "status": "slobodno" }, { "red": "C", "broj": 7, "status": "slobodno" }, { "red": "C", "broj": 8, "status": "slobodno" }, { "red": "C", "broj": 9, "status": "slobodno" }, { "red": "C", "broj": 10, "status": "slobodno" },
        { "red": "D", "broj": 1, "status": "slobodno" }, { "red": "D", "broj": 2, "status": "slobodno" }, { "red": "D", "broj": 3, "status": "slobodno" }, { "red": "D", "broj": 4, "status": "slobodno" }, { "red": "D", "broj": 5, "status": "slobodno" }, { "red": "D", "broj": 6, "status": "slobodno" }, { "red": "D", "broj": 7, "status": "slobodno" }, { "red": "D", "broj": 8, "status": "slobodno" }, { "red": "D", "broj": 9, "status": "slobodno" }, { "red": "D", "broj": 10, "status": "slobodno" },
        { "red": "E", "broj": 1, "status": "slobodno" }, { "red": "E", "broj": 2, "status": "slobodno" }, { "red": "E", "broj": 3, "status": "slobodno" }, { "red": "E", "broj": 4, "status": "slobodno" }, { "red": "E", "broj": 5, "status": "slobodno" }, { "red": "E", "broj": 6, "status": "slobodno" }, { "red": "E", "broj": 7, "status": "slobodno" }, { "red": "E", "broj": 8, "status": "slobodno" }, { "red": "E", "broj": 9, "status": "slobodno" }, { "red": "E", "broj": 10, "status": "slobodno" },
        { "red": "F", "broj": 1, "status": "slobodno" }, { "red": "F", "broj": 2, "status": "slobodno" }, { "red": "F", "broj": 3, "status": "slobodno" }, { "red": "F", "broj": 4, "status": "slobodno" }, { "red": "F", "broj": 5, "status": "slobodno" }, { "red": "F", "broj": 6, "status": "slobodno" }, { "red": "F", "broj": 7, "status": "slobodno" }, { "red": "F", "broj": 8, "status": "slobodno" }, { "red": "F", "broj": 9, "status": "slobodno" }, { "red": "F", "broj": 10, "status": "slobodno" },
        { "red": "G", "broj": 1, "status": "slobodno" }, { "red": "G", "broj": 2, "status": "slobodno" }, { "red": "G", "broj": 3, "status": "slobodno" }, { "red": "G", "broj": 4, "status": "slobodno" }, { "red": "G", "broj": 5, "status": "slobodno" }, { "red": "G", "broj": 6, "status": "slobodno" }, { "red": "G", "broj": 7, "status": "slobodno" }, { "red": "G", "broj": 8, "status": "slobodno" }, { "red": "G", "broj": 9, "status": "slobodno" }, { "red": "G", "broj": 10, "status": "slobodno" },
        { "red": "H", "broj": 1, "status": "slobodno" }, { "red": "H", "broj": 2, "status": "slobodno" }, { "red": "H", "broj": 3, "status": "slobodno" }, { "red": "H", "broj": 4, "status": "slobodno" }, { "red": "H", "broj": 5, "status": "slobodno" }, { "red": "H", "broj": 6, "status": "slobodno" }, { "red": "H", "broj": 7, "status": "slobodno" }, { "red": "H", "broj": 8, "status": "slobodno" }, { "red": "H", "broj": 9, "status": "slobodno" }, { "red": "H", "broj": 10, "status": "slobodno" }
      ]
    },
    {
      "film": "Home Alone",
      "vrijeme": "18:00",
      "sala": "Dvorana 4",
      "trajanje": "103 min",
      "poster": "../slike/sam_u_kuci.webp",
      "sjedista": [
        { "red": "A", "broj": 1, "status": "slobodno" }, { "red": "A", "broj": 2, "status": "slobodno" }, { "red": "A", "broj": 3, "status": "slobodno" }, { "red": "A", "broj": 4, "status": "slobodno" }, { "red": "A", "broj": 5, "status": "slobodno" }, { "red": "A", "broj": 6, "status": "slobodno" }, { "red": "A", "broj": 7, "status": "slobodno" }, { "red": "A", "broj": 8, "status": "slobodno" }, { "red": "A", "broj": 9, "status": "slobodno" }, { "red": "A", "broj": 10, "status": "slobodno" },
        { "red": "B", "broj": 1, "status": "slobodno" }, { "red": "B", "broj": 2, "status": "slobodno" }, { "red": "B", "broj": 3, "status": "slobodno" }, { "red": "B", "broj": 4, "status": "slobodno" }, { "red": "B", "broj": 5, "status": "slobodno" }, { "red": "B", "broj": 6, "status": "slobodno" }, { "red": "B", "broj": 7, "status": "slobodno" }, { "red": "B", "broj": 8, "status": "slobodno" }, { "red": "B", "broj": 9, "status": "slobodno" }, { "red": "B", "broj": 10, "status": "slobodno" },
        { "red": "C", "broj": 1, "status": "zauzeto" }, { "red": "C", "broj": 2, "status": "zauzeto" }, { "red": "C", "broj": 3, "status": "zauzeto" }, { "red": "C", "broj": 4, "status": "slobodno" }, { "red": "C", "broj": 5, "status": "zauzeto" }, { "red": "C", "broj": 6, "status": "zauzeto" }, { "red": "C", "broj": 7, "status": "zauzeto" }, { "red": "C", "broj": 8, "status": "zauzeto" }, { "red": "C", "broj": 9, "status": "slobodno" }, { "red": "C", "broj": 10, "status": "slobodno" },
        { "red": "D", "broj": 1, "status": "slobodno" }, { "red": "D", "broj": 2, "status": "slobodno" }, { "red": "D", "broj": 3, "status": "slobodno" }, { "red": "D", "broj": 4, "status": "slobodno" }, { "red": "D", "broj": 5, "status": "slobodno" }, { "red": "D", "broj": 6, "status": "slobodno" }, { "red": "D", "broj": 7, "status": "slobodno" }, { "red": "D", "broj": 8, "status": "slobodno" }, { "red": "D", "broj": 9, "status": "slobodno" }, { "red": "D", "broj": 10, "status": "slobodno" },
        { "red": "E", "broj": 1, "status": "slobodno" }, { "red": "E", "broj": 2, "status": "slobodno" }, { "red": "E", "broj": 3, "status": "slobodno" }, { "red": "E", "broj": 4, "status": "zauzeto" }, { "red": "E", "broj": 5, "status": "slobodno" }, { "red": "E", "broj": 6, "status": "slobodno" }, { "red": "E", "broj": 7, "status": "slobodno" }, { "red": "E", "broj": 8, "status": "slobodno" }, { "red": "E", "broj": 9, "status": "slobodno" }, { "red": "E", "broj": 10, "status": "slobodno" },
        { "red": "F", "broj": 1, "status": "zauzeto" }, { "red": "F", "broj": 2, "status": "zauzeto" }, { "red": "F", "broj": 3, "status": "zauzeto" }, { "red": "F", "broj": 4, "status": "zauzeto" }, { "red": "F", "broj": 5, "status": "slobodno" }, { "red": "F", "broj": 6, "status": "slobodno" }, { "red": "F", "broj": 7, "status": "zauzeto" }, { "red": "F", "broj": 8, "status": "zauzeto" }, { "red": "F", "broj": 9, "status": "zauzeto" }, { "red": "F", "broj": 10, "status": "slobodno" },
        { "red": "G", "broj": 1, "status": "slobodno" }, { "red": "G", "broj": 2, "status": "slobodno" }, { "red": "G", "broj": 3, "status": "slobodno" }, { "red": "G", "broj": 4, "status": "slobodno" }, { "red": "G", "broj": 5, "status": "slobodno" }, { "red": "G", "broj": 6, "status": "slobodno" }, { "red": "G", "broj": 7, "status": "slobodno" }, { "red": "G", "broj": 8, "status": "slobodno" }, { "red": "G", "broj": 9, "status": "slobodno" }, { "red": "G", "broj": 10, "status": "slobodno" },
        { "red": "H", "broj": 1, "status": "slobodno" }, { "red": "H", "broj": 2, "status": "slobodno" }, { "red": "H", "broj": 3, "status": "zauzeto" }, { "red": "H", "broj": 4, "status": "zauzeto" }, { "red": "H", "broj": 5, "status": "zauzeto" }, { "red": "H", "broj": 6, "status": "zauzeto" }, { "red": "H", "broj": 7, "status": "slobodno" }, { "red": "H", "broj": 8, "status": "slobodno" }, { "red": "H", "broj": 9, "status": "slobodno" }, { "red": "H", "broj": 10, "status": "slobodno" }
      ]
    },
    {
      "film": "Bullet Train",
      "vrijeme": "21:00",
      "sala": "Dvorana 2",
      "trajanje": "126 min",
      "poster": "../slike/bullet_train.jpg",
      "sjedista": [
        { "red": "A", "broj": 1, "status": "slobodno" }, { "red": "A", "broj": 2, "status": "slobodno" }, { "red": "A", "broj": 3, "status": "slobodno" }, { "red": "A", "broj": 4, "status": "slobodno" }, { "red": "A", "broj": 5, "status": "slobodno" }, { "red": "A", "broj": 6, "status": "slobodno" }, { "red": "A", "broj": 7, "status": "slobodno" }, { "red": "A", "broj": 8, "status": "slobodno" }, { "red": "A", "broj": 9, "status": "slobodno" }, { "red": "A", "broj": 10, "status": "slobodno" },
        { "red": "B", "broj": 1, "status": "slobodno" }, { "red": "B", "broj": 2, "status": "slobodno" }, { "red": "B", "broj": 3, "status": "slobodno" }, { "red": "B", "broj": 4, "status": "slobodno" }, { "red": "B", "broj": 5, "status": "slobodno" }, { "red": "B", "broj": 6, "status": "slobodno" }, { "red": "B", "broj": 7, "status": "slobodno" }, { "red": "B", "broj": 8, "status": "slobodno" }, { "red": "B", "broj": 9, "status": "slobodno" }, { "red": "B", "broj": 10, "status": "slobodno" },
        { "red": "C", "broj": 1, "status": "slobodno" }, { "red": "C", "broj": 2, "status": "slobodno" }, { "red": "C", "broj": 3, "status": "slobodno" }, { "red": "C", "broj": 4, "status": "slobodno" }, { "red": "C", "broj": 5, "status": "slobodno" }, { "red": "C", "broj": 6, "status": "slobodno" }, { "red": "C", "broj": 7, "status": "slobodno" }, { "red": "C", "broj": 8, "status": "slobodno" }, { "red": "C", "broj": 9, "status": "zauzeto" }, { "red": "C", "broj": 10, "status": "slobodno" },
        { "red": "D", "broj": 1, "status": "slobodno" }, { "red": "D", "broj": 2, "status": "slobodno" }, { "red": "D", "broj": 3, "status": "zauzeto" }, { "red": "D", "broj": 4, "status": "zauzeto" }, { "red": "D", "broj": 5, "status": "zauzeto" }, { "red": "D", "broj": 6, "status": "zauzeto" }, { "red": "D", "broj": 7, "status": "zauzeto" }, { "red": "D", "broj": 8, "status": "zauzeto" }, { "red": "D", "broj": 9, "status": "slobodno" }, { "red": "D", "broj": 10, "status": "slobodno" },
        { "red": "E", "broj": 1, "status": "slobodno" }, { "red": "E", "broj": 2, "status": "slobodno" }, { "red": "E", "broj": 3, "status": "slobodno" }, { "red": "E", "broj": 4, "status": "slobodno" }, { "red": "E", "broj": 5, "status": "slobodno" }, { "red": "E", "broj": 6, "status": "slobodno" }, { "red": "E", "broj": 7, "status": "slobodno" }, { "red": "E", "broj": 8, "status": "zauzeto" }, { "red": "E", "broj": 9, "status": "slobodno" }, { "red": "E", "broj": 10, "status": "slobodno" },
        { "red": "F", "broj": 1, "status": "slobodno" }, { "red": "F", "broj": 2, "status": "slobodno" }, { "red": "F", "broj": 3, "status": "slobodno" }, { "red": "F", "broj": 4, "status": "zauzeto" }, { "red": "F", "broj": 5, "status": "slobodno" }, { "red": "F", "broj": 6, "status": "zauzeto" }, { "red": "F", "broj": 7, "status": "zauzeto" }, { "red": "F", "broj": 8, "status": "zauzeto" }, { "red": "F", "broj": 9, "status": "slobodno" }, { "red": "F", "broj": 10, "status": "slobodno" },
        { "red": "G", "broj": 1, "status": "slobodno" }, { "red": "G", "broj": 2, "status": "slobodno" }, { "red": "G", "broj": 3, "status": "slobodno" }, { "red": "G", "broj": 4, "status": "zauzeto" }, { "red": "G", "broj": 5, "status": "slobodno" }, { "red": "G", "broj": 6, "status": "slobodno" }, { "red": "G", "broj": 7, "status": "zauzeto" }, { "red": "G", "broj": 8, "status": "slobodno" }, { "red": "G", "broj": 9, "status": "zauzeto" }, { "red": "G", "broj": 10, "status": "zauzeto" },
        { "red": "H", "broj": 1, "status": "slobodno" }, { "red": "H", "broj": 2, "status": "slobodno" }, { "red": "H", "broj": 3, "status": "slobodno" }, { "red": "H", "broj": 4, "status": "slobodno" }, { "red": "H", "broj": 5, "status": "zauzeto" }, { "red": "H", "broj": 6, "status": "slobodno" }, { "red": "H", "broj": 7, "status": "slobodno" }, { "red": "H", "broj": 8, "status": "slobodno" }, { "red": "H", "broj": 9, "status": "slobodno" }, { "red": "H", "broj": 10, "status": "slobodno" }
      ]
    },
    {
      "film": "Spider-Man: Into the Spider-Verse",
      "vrijeme": "17:00",
      "sala": "Dvorana 3",
      "trajanje": "117 min",
      "poster": "../slike/spider_man_into_the_spider_verse.webp",
      "sjedista": [
        { "red": "A", "broj": 1, "status": "slobodno" }, { "red": "A", "broj": 2, "status": "slobodno" }, { "red": "A", "broj": 3, "status": "slobodno" }, { "red": "A", "broj": 4, "status": "slobodno" }, { "red": "A", "broj": 5, "status": "slobodno" }, { "red": "A", "broj": 6, "status": "slobodno" }, { "red": "A", "broj": 7, "status": "slobodno" }, { "red": "A", "broj": 8, "status": "slobodno" }, { "red": "A", "broj": 9, "status": "slobodno" }, { "red": "A", "broj": 10, "status": "slobodno" },
        { "red": "B", "broj": 1, "status": "slobodno" }, { "red": "B", "broj": 2, "status": "zauzeto" }, { "red": "B", "broj": 3, "status": "zauzeto" }, { "red": "B", "broj": 4, "status": "slobodno" }, { "red": "B", "broj": 5, "status": "slobodno" }, { "red": "B", "broj": 6, "status": "slobodno" }, { "red": "B", "broj": 7, "status": "slobodno" }, { "red": "B", "broj": 8, "status": "slobodno" }, { "red": "B", "broj": 9, "status": "slobodno" }, { "red": "B", "broj": 10, "status": "slobodno" },
        { "red": "C", "broj": 1, "status": "zauzeto" }, { "red": "C", "broj": 2, "status": "zauzeto" }, { "red": "C", "broj": 3, "status": "slobodno" }, { "red": "C", "broj": 4, "status": "zauzeto" }, { "red": "C", "broj": 5, "status": "slobodno" }, { "red": "C", "broj": 6, "status": "slobodno" }, { "red": "C", "broj": 7, "status": "zauzeto" }, { "red": "C", "broj": 8, "status": "zauzeto" }, { "red": "C", "broj": 9, "status": "zauzeto" }, { "red": "C", "broj": 10, "status": "zauzeto" },
        { "red": "D", "broj": 1, "status": "slobodno" }, { "red": "D", "broj": 2, "status": "slobodno" }, { "red": "D", "broj": 3, "status": "slobodno" }, { "red": "D", "broj": 4, "status": "zauzeto" }, { "red": "D", "broj": 5, "status": "zauzeto" }, { "red": "D", "broj": 6, "status": "slobodno" }, { "red": "D", "broj": 7, "status": "slobodno" }, { "red": "D", "broj": 8, "status": "slobodno" }, { "red": "D", "broj": 9, "status": "slobodno" }, { "red": "D", "broj": 10, "status": "slobodno" },
        { "red": "E", "broj": 1, "status": "zauzeto" }, { "red": "E", "broj": 2, "status": "zauzeto" }, { "red": "E", "broj": 3, "status": "slobodno" }, { "red": "E", "broj": 4, "status": "slobodno" }, { "red": "E", "broj": 5, "status": "slobodno" }, { "red": "E", "broj": 6, "status": "zauzeto" }, { "red": "E", "broj": 7, "status": "slobodno" }, { "red": "E", "broj": 8, "status": "slobodno" }, { "red": "E", "broj": 9, "status": "slobodno" }, { "red": "E", "broj": 10, "status": "slobodno" },
        { "red": "F", "broj": 1, "status": "slobodno" }, { "red": "F", "broj": 2, "status": "slobodno" }, { "red": "F", "broj": 3, "status": "zauzeto" }, { "red": "F", "broj": 4, "status": "slobodno" }, { "red": "F", "broj": 5, "status": "slobodno" }, { "red": "F", "broj": 6, "status": "zauzeto" }, { "red": "F", "broj": 7, "status": "zauzeto" }, { "red": "F", "broj": 8, "status": "zauzeto" }, { "red": "F", "broj": 9, "status": "zauzeto" }, { "red": "F", "broj": 10, "status": "zauzeto" },
        { "red": "G", "broj": 1, "status": "zauzeto" }, { "red": "G", "broj": 2, "status": "slobodno" }, { "red": "G", "broj": 3, "status": "slobodno" }, { "red": "G", "broj": 4, "status": "slobodno" }, { "red": "G", "broj": 5, "status": "zauzeto" }, { "red": "G", "broj": 6, "status": "zauzeto" }, { "red": "G", "broj": 7, "status": "slobodno" }, { "red": "G", "broj": 8, "status": "slobodno" }, { "red": "G", "broj": 9, "status": "slobodno" }, { "red": "G", "broj": 10, "status": "slobodno" },
        { "red": "H", "broj": 1, "status": "slobodno" }, { "red": "H", "broj": 2, "status": "zauzeto" }, { "red": "H", "broj": 3, "status": "slobodno" }, { "red": "H", "broj": 4, "status": "slobodno" }, { "red": "H", "broj": 5, "status": "slobodno" }, { "red": "H", "broj": 6, "status": "slobodno" }, { "red": "H", "broj": 7, "status": "slobodno" }, { "red": "H", "broj": 8, "status": "slobodno" }, { "red": "H", "broj": 9, "status": "slobodno" }, { "red": "H", "broj": 10, "status": "slobodno" }
      ]
    },
    {
      "film": "Chainsaw Man - The Movie",
      "vrijeme": "20:00",
      "sala": "Dvorana 4",
      "trajanje": "78 min",
      "poster": "../slike/chainsaw_man.webp",
      "sjedista": [
        { "red": "A", "broj": 1, "status": "slobodno" }, { "red": "A", "broj": 2, "status": "slobodno" }, { "red": "A", "broj": 3, "status": "slobodno" }, { "red": "A", "broj": 4, "status": "slobodno" }, { "red": "A", "broj": 5, "status": "slobodno" }, { "red": "A", "broj": 6, "status": "slobodno" }, { "red": "A", "broj": 7, "status": "slobodno" }, { "red": "A", "broj": 8, "status": "slobodno" }, { "red": "A", "broj": 9, "status": "slobodno" }, { "red": "A", "broj": 10, "status": "slobodno" },
        { "red": "B", "broj": 1, "status": "slobodno" }, { "red": "B", "broj": 2, "status": "slobodno" }, { "red": "B", "broj": 3, "status": "slobodno" }, { "red": "B", "broj": 4, "status": "slobodno" }, { "red": "B", "broj": 5, "status": "slobodno" }, { "red": "B", "broj": 6, "status": "zauzeto" }, { "red": "B", "broj": 7, "status": "zauzeto" }, { "red": "B", "broj": 8, "status": "slobodno" }, { "red": "B", "broj": 9, "status": "slobodno" }, { "red": "B", "broj": 10, "status": "slobodno" },
        { "red": "C", "broj": 1, "status": "zauzeto" }, { "red": "C", "broj": 2, "status": "zauzeto" }, { "red": "C", "broj": 3, "status": "zauzeto" }, { "red": "C", "broj": 4, "status": "slobodno" }, { "red": "C", "broj": 5, "status": "zauzeto" }, { "red": "C", "broj": 6, "status": "slobodno" }, { "red": "C", "broj": 7, "status": "slobodno" }, { "red": "C", "broj": 8, "status": "slobodno" }, { "red": "C", "broj": 9, "status": "slobodno" }, { "red": "C", "broj": 10, "status": "slobodno" },
        { "red": "D", "broj": 1, "status": "zauzeto" }, { "red": "D", "broj": 2, "status": "zauzeto" }, { "red": "D", "broj": 3, "status": "zauzeto" }, { "red": "D", "broj": 4, "status": "slobodno" }, { "red": "D", "broj": 5, "status": "zauzeto" }, { "red": "D", "broj": 6, "status": "zauzeto" }, { "red": "D", "broj": 7, "status": "zauzeto" }, { "red": "D", "broj": 8, "status": "zauzeto" }, { "red": "D", "broj": 9, "status": "slobodno" }, { "red": "D", "broj": 10, "status": "slobodno" },
        { "red": "E", "broj": 1, "status": "zauzeto" }, { "red": "E", "broj": 2, "status": "zauzeto" }, { "red": "E", "broj": 3, "status": "zauzeto" }, { "red": "E", "broj": 4, "status": "zauzeto" }, { "red": "E", "broj": 5, "status": "zauzeto" }, { "red": "E", "broj": 6, "status": "zauzeto" }, { "red": "E", "broj": 7, "status": "zauzeto" }, { "red": "E", "broj": 8, "status": "zauzeto" }, { "red": "E", "broj": 9, "status": "slobodno" }, { "red": "E", "broj": 10, "status": "slobodno" },
        { "red": "F", "broj": 1, "status": "slobodno" }, { "red": "F", "broj": 2, "status": "slobodno" }, { "red": "F", "broj": 3, "status": "slobodno" }, { "red": "F", "broj": 4, "status": "slobodno" }, { "red": "F", "broj": 5, "status": "slobodno" }, { "red": "F", "broj": 6, "status": "slobodno" }, { "red": "F", "broj": 7, "status": "slobodno" }, { "red": "F", "broj": 8, "status": "slobodno" }, { "red": "F", "broj": 9, "status": "slobodno" }, { "red": "F", "broj": 10, "status": "slobodno" },
        { "red": "G", "broj": 1, "status": "zauzeto" }, { "red": "G", "broj": 2, "status": "slobodno" }, { "red": "G", "broj": 3, "status": "slobodno" }, { "red": "G", "broj": 4, "status": "slobodno" }, { "red": "G", "broj": 5, "status": "zauzeto" }, { "red": "G", "broj": 6, "status": "zauzeto" }, { "red": "G", "broj": 7, "status": "zauzeto" }, { "red": "G", "broj": 8, "status": "slobodno" }, { "red": "G", "broj": 9, "status": "slobodno" }, { "red": "G", "broj": 10, "status": "slobodno" },
        { "red": "H", "broj": 1, "status": "zauzeto" }, { "red": "H", "broj": 2, "status": "slobodno" }, { "red": "H", "broj": 3, "status": "slobodno" }, { "red": "H", "broj": 4, "status": "slobodno" }, { "red": "H", "broj": 5, "status": "slobodno" }, { "red": "H", "broj": 6, "status": "slobodno" }, { "red": "H", "broj": 7, "status": "slobodno" }, { "red": "H", "broj": 8, "status": "slobodno" }, { "red": "H", "broj": 9, "status": "slobodno" }, { "red": "H", "broj": 10, "status": "slobodno" }
      ]
    },
    {
      "film": "End of Evangelion",
      "vrijeme": "22:00",
      "sala": "Dvorana 1",
      "trajanje": "87 min",
      "poster": "../slike/evangelion.webp",
      "sjedista": [
        { "red": "A", "broj": 1, "status": "slobodno" }, { "red": "A", "broj": 2, "status": "slobodno" }, { "red": "A", "broj": 3, "status": "slobodno" }, { "red": "A", "broj": 4, "status": "slobodno" }, { "red": "A", "broj": 5, "status": "slobodno" }, { "red": "A", "broj": 6, "status": "slobodno" }, { "red": "A", "broj": 7, "status": "slobodno" }, { "red": "A", "broj": 8, "status": "slobodno" }, { "red": "A", "broj": 9, "status": "slobodno" }, { "red": "A", "broj": 10, "status": "slobodno" },
        { "red": "B", "broj": 1, "status": "slobodno" }, { "red": "B", "broj": 2, "status": "slobodno" }, { "red": "B", "broj": 3, "status": "slobodno" }, { "red": "B", "broj": 4, "status": "slobodno" }, { "red": "B", "broj": 5, "status": "slobodno" }, { "red": "B", "broj": 6, "status": "slobodno" }, { "red": "B", "broj": 7, "status": "slobodno" }, { "red": "B", "broj": 8, "status": "zauzeto" }, { "red": "B", "broj": 9, "status": "zauzeto" }, { "red": "B", "broj": 10, "status": "zauzeto" },
        { "red": "C", "broj": 1, "status": "zauzeto" }, { "red": "C", "broj": 2, "status": "zauzeto" }, { "red": "C", "broj": 3, "status": "zauzeto" }, { "red": "C", "broj": 4, "status": "zauzeto" }, { "red": "C", "broj": 5, "status": "slobodno" }, { "red": "C", "broj": 6, "status": "slobodno" }, { "red": "C", "broj": 7, "status": "slobodno" }, { "red": "C", "broj": 8, "status": "slobodno" }, { "red": "C", "broj": 9, "status": "slobodno" }, { "red": "C", "broj": 10, "status": "slobodno" },
        { "red": "D", "broj": 1, "status": "slobodno" }, { "red": "D", "broj": 2, "status": "slobodno" }, { "red": "D", "broj": 3, "status": "zauzeto" }, { "red": "D", "broj": 4, "status": "slobodno" }, { "red": "D", "broj": 5, "status": "zauzeto" }, { "red": "D", "broj": 6, "status": "zauzeto" }, { "red": "D", "broj": 7, "status": "zauzeto" }, { "red": "D", "broj": 8, "status": "zauzeto" }, { "red": "D", "broj": 9, "status": "zauzeto" }, { "red": "D", "broj": 10, "status": "zauzeto" },
        { "red": "E", "broj": 1, "status": "slobodno" }, { "red": "E", "broj": 2, "status": "slobodno" }, { "red": "E", "broj": 3, "status": "slobodno" }, { "red": "E", "broj": 4, "status": "slobodno" }, { "red": "E", "broj": 5, "status": "zauzeto" }, { "red": "E", "broj": 6, "status": "slobodno" }, { "red": "E", "broj": 7, "status": "slobodno" }, { "red": "E", "broj": 8, "status": "slobodno" }, { "red": "E", "broj": 9, "status": "slobodno" }, { "red": "E", "broj": 10, "status": "slobodno" },
        { "red": "F", "broj": 1, "status": "slobodno" }, { "red": "F", "broj": 2, "status": "zauzeto" }, { "red": "F", "broj": 3, "status": "zauzeto" }, { "red": "F", "broj": 4, "status": "zauzeto" }, { "red": "F", "broj": 5, "status": "slobodno" }, { "red": "F", "broj": 6, "status": "slobodno" }, { "red": "F", "broj": 7, "status": "slobodno" }, { "red": "F", "broj": 8, "status": "zauzeto" }, { "red": "F", "broj": 9, "status": "zauzeto" }, { "red": "F", "broj": 10, "status": "slobodno" },
        { "red": "G", "broj": 1, "status": "zauzeto" }, { "red": "G", "broj": 2, "status": "slobodno" }, { "red": "G", "broj": 3, "status": "slobodno" }, { "red": "G", "broj": 4, "status": "slobodno" }, { "red": "G", "broj": 5, "status": "slobodno" }, { "red": "G", "broj": 6, "status": "slobodno" }, { "red": "G", "broj": 7, "status": "slobodno" }, { "red": "G", "broj": 8, "status": "slobodno" }, { "red": "G", "broj": 9, "status": "slobodno" }, { "red": "G", "broj": 10, "status": "slobodno" },
        { "red": "H", "broj": 1, "status": "slobodno" }, { "red": "H", "broj": 2, "status": "slobodno" }, { "red": "H", "broj": 3, "status": "slobodno" }, { "red": "H", "broj": 4, "status": "slobodno" }, { "red": "H", "broj": 5, "status": "slobodno" }, { "red": "H", "broj": 6, "status": "slobodno" }, { "red": "H", "broj": 7, "status": "slobodno" }, { "red": "H", "broj": 8, "status": "zauzeto" }, { "red": "H", "broj": 9, "status": "zauzeto" }, { "red": "H", "broj": 10, "status": "zauzeto" }
      ]
    }
  ]
};
